In [3]:
import pandas as pd
import numpy as np
import torch

In [4]:
labels_df=pd.read_csv("elliptic_bitcoin_dataset/elliptic_txs_classes.csv")
edges_df=pd.read_csv("elliptic_bitcoin_dataset/elliptic_txs_edgelist.csv")
features_df=pd.read_csv("elliptic_bitcoin_dataset/elliptic_txs_features.csv",header=None)

In [5]:
features_df.rename(columns={0:"txId"},inplace=True)
features_df

txId   1         2         3         4          5         6  \
0       230425980   1 -0.171469 -0.184668 -1.201369  -0.121970 -0.043875   
1         5530458   1 -0.171484 -0.184668 -1.201369  -0.121970 -0.043875   
2       232022460   1 -0.172107 -0.184668 -1.201369  -0.121970 -0.043875   
3       232438397   1  0.163054  1.963790 -0.646376  12.409294 -0.063725   
4       230460314   1  1.011523 -0.081127 -1.201369   1.153668  0.333276   
...           ...  ..       ...       ...       ...        ...       ...   
203764  173077460  49 -0.145771 -0.163752  0.463609  -0.121970 -0.043875   
203765  158577750  49 -0.165920 -0.123607  1.018602  -0.121970 -0.043875   
203766  158375402  49 -0.172014 -0.078182  1.018602   0.028105 -0.043875   
203767  158654197  49 -0.172842 -0.176622  1.018602  -0.121970 -0.043875   
203768  157597225  49 -0.012037 -0.132276  0.463609  -0.121970 -0.043875   

               7          8         9  ...       157       158       159  \
0      -0.113002  -0.061584 -0.162097  ... -0.562153 -0.600999  1.461330   
1      -0.113002  -0.061584 -0.162112  ...  0.947382  0.673103 -0.979074   
2      -0.113002  -0.061584 -0.162749  ...  0.670883  0.439728 -0.979074   
3       9.782742  12.414558 -0.163645  ... -0.577099 -0.613614  0.241128   
4       1.312656  -0.061584 -0.163523  ... -0.511871 -0.400422  0.517257   
...          ...        ...       ...  ...       ...       ...       ...   
203764 -0.113002  -0.061584 -0.135803  ... -0.577099 -0.613614  0.241128   
203765 -0.113002  -0.061584 -0.156418  ...  0.162722  0.010822  1.461330   
203766  0.054722  -0.061584 -0.163626  ...  1.261246  1.985050  1.461330   
203767 -0.113002  -0.061584 -0.163501  ... -0.397749 -0.411776  1.461330   
203768 -0.113002  -0.061584  0.001027  ... -0.577099 -0.613614  0.241128   

             160       161       162       163       164       165       166  
0       1.461369  0.018279 -0.087490 -0.131155 -0.097524 -0.120613 -0.119792  
1      -0.978556  0.018279 -0.087490 -0.131155 -0.097524 -0.120613 -0.119792  
2      -0.978556 -0.098889 -0.106715 -0.131155 -0.183671 -0.120613 -0.119792  
3       0.241406  1.072793  0.085530 -0.131155  0.677799 -0.120613 -0.119792  
4       0.579382  0.018279  0.277775  0.326394  1.293750  0.178136  0.179117  
...          ...       ...       ...       ...       ...       ...       ...  
203764  0.241406  0.018279 -0.087490 -0.131155 -0.097524 -0.120613 -0.119792  
203765  1.461369 -0.098889 -0.087490 -0.084674 -0.140597 -1.760926 -1.760984  
203766  1.461369  0.018279 -0.087490 -0.131155 -0.097524 -0.120613 -0.119792  
203767  1.461369 -0.098889 -0.087490 -0.084674 -0.140597  1.519700  1.521399  
203768  0.241406 -0.098889 -0.087490 -0.084674 -0.140597  1.519700  1.521399  

[203769 rows x 167 columns]

In [6]:
edges_df

txId1      txId2
0       230425980    5530458
1       232022460  232438397
2       230460314  230459870
3       230333930  230595899
4       232013274  232029206
...           ...        ...
234350  158365409  157930723
234351  188708874  188708879
234352  157659064  157659046
234353   87414554  106877725
234354  158589452  158589457

[234355 rows x 2 columns]

In [7]:
labels_df

txId    class
0       230425980  unknown
1         5530458  unknown
2       232022460  unknown
3       232438397        2
4       230460314  unknown
...           ...      ...
203764  173077460  unknown
203765  158577750  unknown
203766  158375402        1
203767  158654197  unknown
203768  157597225  unknown

[203769 rows x 2 columns]

### Features Scaling and txid:idx ratio

In [9]:
from sklearn.preprocessing import StandardScaler
features = features_df.drop(columns=["txId"]).values
scaler = StandardScaler()
features = scaler.fit_transform(features)
features

array([[-1.50565256, -0.17146929, -0.18466755, ..., -0.09752359,
        -0.12061341, -0.11979246],
       [-1.50565256, -0.17148421, -0.18466755, ..., -0.09752359,
        -0.12061341, -0.11979246],
       [-1.50565256, -0.17210694, -0.18466755, ..., -0.18367056,
        -0.12061341, -0.11979246],
       ...,
       [ 1.6580424 , -0.17201373, -0.07818172, ..., -0.09752359,
        -0.12061341, -0.11979246],
       [ 1.6580424 , -0.17284167, -0.17662248, ..., -0.14059708,
         1.51969962,  1.52139948],
       [ 1.6580424 , -0.01203726, -0.13227626, ..., -0.14059708,
         1.51969962,  1.52139948]])

In [10]:
x = torch.tensor(features, dtype=torch.float)
x

tensor([[-1.5057, -0.1715, -0.1847,  ..., -0.0975, -0.1206, -0.1198],
        [-1.5057, -0.1715, -0.1847,  ..., -0.0975, -0.1206, -0.1198],
        [-1.5057, -0.1721, -0.1847,  ..., -0.1837, -0.1206, -0.1198],
        ...,
        [ 1.6580, -0.1720, -0.0782,  ..., -0.0975, -0.1206, -0.1198],
        [ 1.6580, -0.1728, -0.1766,  ..., -0.1406,  1.5197,  1.5214],
        [ 1.6580, -0.0120, -0.1323,  ..., -0.1406,  1.5197,  1.5214]])

In [11]:
txid_to_idx={txId:idx for idx,txId in enumerate(features_df["txId"])}
txid_to_idx

{230425980: 0,
 5530458: 1,
 232022460: 2,
 232438397: 3,
 230460314: 4,
 230459870: 5,
 230333930: 6,
 230595899: 7,
 232013274: 8,
 232029206: 9,
 232344069: 10,
 27553029: 11,
 36411953: 12,
 230405052: 13,
 34194980: 14,
 5529846: 15,
 3881097: 16,
 232457116: 17,
 230409257: 18,
 32877982: 19,
 230351738: 20,
 195218118: 21,
 88008478: 22,
 232012569: 23,
 232412408: 24,
 232412405: 25,
 232038018: 26,
 232470342: 27,
 2925426: 28,
 230550393: 29,
 232051089: 30,
 232470704: 31,
 233591710: 32,
 234439913: 33,
 232945017: 34,
 94251207: 35,
 6595740: 36,
 79840192: 37,
 212704383: 38,
 212366182: 39,
 69254632: 40,
 230595355: 41,
 166890641: 42,
 82304496: 43,
 232033533: 44,
 230470022: 45,
 230598493: 46,
 43560505: 47,
 14878322: 48,
 230415750: 49,
 232073372: 50,
 75604335: 51,
 230473487: 52,
 7089694: 53,
 231179595: 54,
 3307463: 55,
 230658679: 56,
 232074274: 57,
 5234549: 58,
 231177927: 59,
 232431877: 60,
 2758467: 61,
 81273879: 62,
 232437171: 63,
 3878856: 64,
 38

### edges src->dest in index format

In [13]:
edge_index = torch.tensor([
    [txid_to_idx[src] for src in edges_df["txId1"]],
    [txid_to_idx[dst] for dst in edges_df["txId2"]]
], dtype=torch.long)
edge_index

tensor([[     0,      2,      4,  ..., 201921, 201480, 201954],
        [     1,      3,      5,  ..., 202042, 201368, 201756]])

### labels encode and store in dict format for easy access

In [15]:
labels_map={"unknown":-1,"2":0,"1":1}
labels_df["class"]=labels_df["class"].replace(labels_map)
labels_df


/var/folders/kk/18b3yzps28q_cvvqn195k0c00000gn/T/ipykernel_4180/421995102.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  labels_df["class"]=labels_df["class"].replace(labels_map)


txId  class
0       230425980     -1
1         5530458     -1
2       232022460     -1
3       232438397      0
4       230460314     -1
...           ...    ...
203764  173077460     -1
203765  158577750     -1
203766  158375402      1
203767  158654197     -1
203768  157597225     -1

[203769 rows x 2 columns]

In [16]:
label_dict=dict(zip(labels_df["txId"],labels_df["class"]))
label_dict

{230425980: -1,
 5530458: -1,
 232022460: -1,
 232438397: 0,
 230460314: -1,
 230459870: -1,
 230333930: -1,
 230595899: -1,
 232013274: -1,
 232029206: 0,
 232344069: 0,
 27553029: 0,
 36411953: -1,
 230405052: -1,
 34194980: -1,
 5529846: -1,
 3881097: 0,
 232457116: 0,
 230409257: -1,
 32877982: -1,
 230351738: -1,
 195218118: -1,
 88008478: -1,
 232012569: -1,
 232412408: -1,
 232412405: 0,
 232038018: -1,
 232470342: 0,
 2925426: -1,
 230550393: 0,
 232051089: 0,
 232470704: 0,
 233591710: -1,
 234439913: -1,
 232945017: -1,
 94251207: -1,
 6595740: -1,
 79840192: -1,
 212704383: -1,
 212366182: -1,
 69254632: -1,
 230595355: -1,
 166890641: -1,
 82304496: -1,
 232033533: 0,
 230470022: -1,
 230598493: -1,
 43560505: -1,
 14878322: -1,
 230415750: -1,
 232073372: -1,
 75604335: -1,
 230473487: 0,
 7089694: 0,
 231179595: 0,
 3307463: -1,
 230658679: -1,
 232074274: -1,
 5234549: -1,
 231177927: 0,
 232431877: -1,
 2758467: 0,
 81273879: -1,
 232437171: 0,
 3878856: -1,
 3878886: 0

In [17]:
labels = [label_dict.get(tx_id, -1) for tx_id in features_df["txId"]]
labels

[-1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 0,
 -1,
 0,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 0,
 -1,
 0,
 -1,
 0,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 -1,
 -1,
 0,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 0,
 0,
 -1,
 0,
 -1,
 -1,
 0,
 0,
 -1,
 0,
 0,
 0,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 0,
 0,
 0,
 -1,
 0,
 -1,
 -1,
 0,
 0,
 0,
 -1,
 0,
 -1,
 0,
 0,
 -1,
 0,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 0,
 0,
 0,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 -1,
 -1,
 0,
 0,
 -1,
 -1,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 

In [18]:
labels=torch.tensor(labels,dtype=torch.long)
labels

tensor([-1, -1, -1,  ...,  1, -1, -1])

## Create pytorch geometric data obj

In [20]:
from torch_geometric.data import Data
data= Data(x=x, edge_index=edge_index,y=labels)
data

Data(x=[203769, 166], edge_index=[2, 234355], y=[203769])

## Split

In [22]:
from sklearn.model_selection import train_test_split

labeled_idx=(data.y != -1).nonzero(as_tuple=True)[0]
y_labeled=data.y[labeled_idx]
y_labeled

tensor([0, 0, 0,  ..., 1, 0, 1])

In [23]:
# Split into train/val/test
train_idx, temp_idx = train_test_split(labeled_idx, test_size=0.3, stratify=y_labeled, random_state=42)
val_idx, test_idx = train_test_split(temp_idx, test_size=0.5, stratify=data.y[temp_idx], random_state=42)

In [24]:
# create masks
#initally all nodes are false
data.train_mask=torch.zeros(data.num_nodes,dtype=torch.bool)
data.val_mask=torch.zeros(data.num_nodes,dtype=torch.bool)
data.test_mask=torch.zeros(data.num_nodes,dtype=torch.bool)

#make true for some nodes
data.train_mask[train_idx] = True
data.val_mask[val_idx] = True
data.test_mask[test_idx] = True

print(f"Train: {data.train_mask.sum().item()}, Val: {data.val_mask.sum().item()}, Test: {data.test_mask.sum().item()}")

Train: 32594, Val: 6985, Test: 6985


## Define GNN model 1)define layers 2)move to device 3)define fwd funcn

In [26]:
from torch_geometric.nn import GCNConv

conv1=GCNConv(in_channels=166,out_channels=64)
conv2=GCNConv(in_channels=64,out_channels=2)

device= torch.device('cuda' if torch.cuda.is_available() else 'cpu')
conv1=conv1.to(device)
conv2=conv2.to(device)
data=data.to(device)


In [27]:
import torch.nn.functional as AF

def forward(data):
    x, edge_index=data.x,data.edge_index
    x=conv1(x,edge_index)
    x=AF.relu(x)
    x=conv2(x,edge_index)
    return x

## Model Training

In [29]:
import torch.optim as optim
import torch.nn as nn

optimizer=optim.Adam(list(conv1.parameters())+list(conv2.parameters()),lr=0.01,weight_decay=5e-4)
criterion=nn.CrossEntropyLoss()

In [30]:
def train():
    conv1.train()
    conv2.train()
    optimizer.zero_grad()
    out=forward(data)
    loss=criterion(out[data.train_mask],data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    return loss.item()

In [31]:
def evaluate(mask):
    conv1.eval()
    conv2.eval()
    out=forward(data)
    preds=out[mask].argmax(dim=1)
    acc=(preds == data.y[mask]).sum().item() / mask.sum().item()
    return acc

In [32]:
for epoch in range(1, 201):
    loss = train()
    val_acc = evaluate(data.val_mask)
    if epoch % 20 == 0:
        print(f"Epoch {epoch:03d}, Loss: {loss:.4f}, Val Acc: {val_acc:.4f}")

Epoch 020, Loss: 0.1994, Val Acc: 0.9350
Epoch 040, Loss: 0.1600, Val Acc: 0.9442
Epoch 060, Loss: 0.1436, Val Acc: 0.9455
Epoch 080, Loss: 0.1328, Val Acc: 0.9497
Epoch 100, Loss: 0.1245, Val Acc: 0.9515
Epoch 120, Loss: 0.1174, Val Acc: 0.9536
Epoch 140, Loss: 0.1113, Val Acc: 0.9559
Epoch 160, Loss: 0.1056, Val Acc: 0.9559
Epoch 180, Loss: 0.1007, Val Acc: 0.9585
Epoch 200, Loss: 0.0970, Val Acc: 0.9585


In [33]:
test_acc = evaluate(data.test_mask)
print(f"Test Accuracy: {test_acc:.4f}")

Test Accuracy: 0.9623


In [34]:
from sklearn.metrics import classification_report

conv1.eval()
conv2.eval()
out = forward(data)

preds = out[data.test_mask].argmax(dim=1).cpu().numpy()
true = data.y[data.test_mask].cpu().numpy()

print(classification_report(true, preds, target_names=["licit", "illicit"]))

              precision    recall  f1-score   support

       licit       0.97      0.99      0.98      6303
     illicit       0.87      0.73      0.79       682

    accuracy                           0.96      6985
   macro avg       0.92      0.86      0.88      6985
weighted avg       0.96      0.96      0.96      6985



In [35]:
torch.save({
    'conv1': conv1.state_dict(),
    'conv2': conv2.state_dict()
}, "gnn_elliptic_model.pth")